  commitFormat: angular
branch:
  master: release
release: 'github'
github:
  repo: "go-semantic-release"
  user: "nightapes"
assets:
  - name: ./build/webm-api_windows_amd64.exe
    compress: false
  - name: ./build/webm-api_linux_amd64
    compress: false
  - name: ./build/webm-api_darwin_amd64
    compress: false
  - name: ./build/webm-api_darwin_arm64
    compress: false
hooks:
  preRelease:
    - name: echo $RELEASE_VERSION
  postRelease:
    - name: echo $RELEASE_VERSION