### Get files
POST http://localhost:3000/filesByCondition
Accept: application/json
Content-Type: application/json

{ "2ch": ["b"] }

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received ${type}`);
    });

    client.test("Response is correct JSON struct", function() {
        client.assert(Array.isArray(response.body), "Expected array of items");
        client.assert("file" in response.body[0], "Expected file field in array element");
    });
%}