name: Release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: go get -u -v
      - run: go build
      - uses: actions/setup-node@v1
      - run: npm i @semantic-release/git @semantic-release/github
      - run: npx semantic-release