name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i @semantic-release/git @semantic-release/github @semantic-release/exec
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: npx semantic-release