name: Release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: go install github.com/goreleaser/goreleaser@latest
      - run: export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" goreleaser release